services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: database
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    command: ["redis-server", "--requirepass", "secret"]
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data

  server:
    build: ./server
    container_name: server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://root:secret@mongo:27018/database?authSource=admin
      - REDIS_URI=redis://:secret@redis:6378
    depends_on:
      - mongo
      - redis

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://server:3001
    depends_on:
      - server

volumes:
  mongo_data:
  redis_data: